import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from './Header'
const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>넥스트.js 타입스크립트 연습</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
  <Header/>

    </div>
  )
}

export default Home
